version: "3.3"

services:

  # MySQL
  db:
    container_name: "db"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: devfest
      MYSQL_USER: cpprhtn
      MYSQL_PASSWORD: 12341234
      MYSQL_ROOT_PASSWORD: 12341234
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - local-net


  # FastAPI
  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8800:8800"
    volumes:
      - ./code:/usr/src/server
    networks:
      - local-net


networks:
  local-net:
    driver: bridge
